### ISSUE TITLE
setUp and skipped = True

### ISSUE THREAD

**Issue by t0ster** [Almad/django-sane-testing#32]
If use `setUp()` and mark test as skipped it would fail.

How to reproduce:

```
class TestTests(UnitTestCase):
    def setUp(self):
        # Setting up ...
        pass

    def failing_skipped_test(self):
        assert False

TestTests.skipped = True
```

**Comment by Almad** [comment]
Yes, You should call super() in setUp/tearDown, or bad things may happen.

This is not mentioned in docs, however, and should be.

Also, marking test as skipped should be done via

```
raise self.SkipTest
```

instead of class attribute -- attribute is used only as an workaround for test selection plugin (because raising SkipTest in some plugin stages causes bad plugin interaction).

**Comment by Almad** [comment]
Follow-up is ticket #33
